version: '3.8'
services:
  auth_service:
    container_name: auth_service
    command: npm run start
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    ports:
      - 4000:4000
